spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://192.168.1.100:5440/simpleproject
    username: root
    password: passwordroot
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none

jwt:
  private.key: classpath:private.key
  public.key: classpath:public.key
  duration: 3600